run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  # Enable all checks (which was as default disabled e.g. comments).
  exclude-use-default: false

  exclude-rules:
    # Documenting comments are not required except on packages.
    - linters:
        - revive
      text: exported (function|method|type) .*? should have comment or be unexported
    - linters:
        - revive
      text: exported (const|var) .*? should have comment (\(or a comment on this block\) )?or be unexported
    - linters:
        - revive
      text: "if-return: redundant if ...; err != nil check, just return error instead."

  # Value 0 means show all.
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  goimports:
    # Put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes.
    local-prefixes: github.com/nobl9/n9
  govet:
    # Report about shadowed variables.
    check-shadowing: true
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      # - diagnostic
      - opinionated
      # - style
  exhaustive:
    # In switch statement treat label default: as being exhaustive.
    default-signifies-exhaustive: true
  misspell:
    locale: US
    ignore-words:
    - analyses

linters:
  # Please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint.
  disable-all: true
  enable:
    # All linters from list https://golangci-lint.run/usage/linters/ are speciefed here and explicit enable/disable.
    - asciicheck
    - bodyclose
    # - cyclop # Nice! to considers
    - deadcode
    - depguard
    - dogsled
    # - durationcheck # Nice! Enable in separate PR.
    - errcheck
    # - errorlint # Nice! To consider, enable in separate PR.
    - exhaustive
    # - exhaustivestruct # Should be used only in special cases, for N9 is useless.
    - exportloopref
    # - forbidigo # Nice! Not ready now.
    # - funlen # About optimal function length programmer and reviewer should decide.
    # - gci # Nice! Enable in separate PR.
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # - godot # Nice! Enable in separate PR.
    # - godox
    # - goerr113 # To consider.
    - gofmt
    # - gofumpt # Nice! Not ready now.
    - goheader
    - goimports
    # - golint # Deprecated and replaced by revive, since 1.40 golangci-lint.
    # - gomnd # Too aggressive, programmer and reviewer should decide what "magic numbers" is inappropriate in code.
    - goprintffuncname
    # - gosec # Commented out because it's used directly
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    # - nestif # Nice! Not ready now.
    - nilerr
    # - nlreturn # In some cases try to force redundant empty lines, which contradicts the style guide.
    # - noctx # Nice! not ready now
    # - nolintlint # To consider.
    # - paralleltest # To consider.
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    # - testpackage # Forces separate _test packages. In N9 there're tests already which doesn't follow this.
    # - thelper # Force explicit marking of helper functions.
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    # - wrapcheck # Requires every error returned from third-party library to be wrapped.
    - varcheck
    # - wsl # Try to force redundant empty lines in some cases, which contradicts the style guide.