version: "1.0"

hooks:
  on_fail:
    steps:
      # Notify about pipeline failure only for main
      notify:
        when:
          branch:
            only:
              - main
        image: codefresh/slacknotifier
        environment:
          - 'SLACK_HOOK_URL=${{SLACK_WEBHOOK}}'
          - 'SLACK_TEXT=Pipeline failed for Nobl9 Terraform Provider repository'
          - 'SLACK_ATTACHMENTS=[{ "color":"#d00000", "blocks":[{"type":"context", "elements":[ { "type":"plain_text","text":"Pipeline failed for Nobl9 Terraform Provider repository", "emoji":true }]}]}]'
          - 'SLACK_USER_NAME=Nobl9 Terraform Provider'
          - 'SLACK_ICON_EMOJI=:terraform:'

stages:
  - "clone"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "nobl9/terraform-provider-nobl9"
    revision: "${{CF_REVISION}}"
    git: "github"
    stage: "clone"

  test:
    title: "Running test"
    type: "freestyle"
    image: "hashicorp/terraform:1.2.5"
    working_directory: "${{clone}}"
    commands:
      - "apk add go make"
      - "make testacc"
    stage: "test"
