name: Acceptance tests
on:
  workflow_call:
    inputs:
      clientId:
        description: Client ID to use for authentication
        required: true
        type: string
      oktaOrgUrl:
        description: Okta organization URL
        required: false
        type: string
      oktaAuthServer:
        description: Okta authentication server identifier
        required: false
        type: string
      project:
        description: Project name to create the tested objects in
        required: false
        type: string
      ref:
        description: Reference branch, tag or commit SHA to checkout
        required: false
        type: string
        default: main
    secrets:
      clientSecret:
        description: Client secret to use for authentication
        required: true
jobs:
  test:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          repository: nobl9/terraform-provider-nobl9
          ref: ${{ inputs.ref }}
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false
      # If we don't pre-install Terraform, the parallel acceptance tests might fail.
      # See https://github.com/hashicorp/terraform-plugin-testing/issues/429.
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Run acceptance tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: make test/acc
        env:
          NOBL9_CLIENT_ID: "${{ inputs.clientId }}"
          NOBL9_CLIENT_SECRET: "${{ secrets.clientSecret }}"
          NOBL9_OKTA_URL: "${{ inputs.oktaOrgUrl }}"
          NOBL9_OKTA_AUTH: "${{ inputs.oktaAuthServer }}"
          NOBL9_PROJECT: "${{ inputs.project }}"
          NOBL9_NO_CONFIG_FILE: false
