name: Acceptance tests manual dispatch
on:
  workflow_dispatch:
    inputs:
      clientId:
        description: Client ID to use for authentication
        required: true
        type: string
      clientSecret:
        description: Client Secret to use for authentication
        required: true
        type: string
      oktaOrgUrl:
        description: Okta organization URL
        required: false
        type: string
      oktaAuthServer:
        description: Okta authentication server identifier
        required: false
        type: string
      project:
        description: Project to create the test objects in
        required: false
        type: string
jobs:
  test:
    uses: ./.github/workflows/acc-tests.yml
    with:
      clientId: "${{ inputs.clientId }}"
      clientSecret: "${{ inputs.clientSecret }}"
      oktaOrgUrl: "${{ inputs.oktaOrgUrl }}"
      oktaAuthServer: "${{ inputs.oktaAuthServer }}"
      project: "{{ inputs.project }}"
