name: Release candidate
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-"
jobs:
  test:
    uses: ./.github/workflows/acc-tests.yml
    with:
      clientId: "${{ vars.TERRAFORM_NOBL9_CLIENT_ID }}"
      project: "${{ vars.TERRAFORM_NOBL9_PROJECT }}"
      ref: "${{ github.ref_name }}"
    secrets:
      clientSecret: "${{ secrets.TERRAFORM_NOBL9_CLIENT_SECRET }}"
